# Generated by Django 5.0.8 on 2024-09-04 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ticker', models.CharField(max_length=6, unique=True)),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('date', models.DateField()),
                ('change', models.DecimalField(decimal_places=4, max_digits=19)),
                ('change_percentage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('volume', models.IntegerField()),
                ('slug', models.SlugField(blank=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.stock', unique_for_date='price')),
            ],
        ),
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('date', models.DateField()),
                ('volume', models.IntegerField()),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.stockprice')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.stock', unique_for_date='date')),
            ],
        ),
    ]
