# Generated by Django 4.2.14 on 2024-08-02 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=5)),
                ('change_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volume', models.IntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='slug',
            field=models.SlugField(default='blank'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StockTransactions',
        ),
        migrations.AddField(
            model_name='stockimport',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.stock'),
        ),
    ]
