# Generated by Django 5.0.8 on 2024-09-02 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_stock_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.stockprice'),
        ),
    ]
