# Generated by Django 4.2.14 on 2024-08-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_stockimport_stock_slug_delete_stocktransactions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='stockimport',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
