# Generated by Django 5.0.8 on 2024-09-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_stockprice_previous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprice',
            name='slug',
        ),
    ]
