# Generated by Django 4.2.14 on 2024-08-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_alter_stock_slug_alter_stockimport_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=6),
        ),
    ]
