# Generated by Django 4.2.14 on 2024-08-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_stock_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockimport',
            name='change',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
        migrations.AlterField(
            model_name='stockimport',
            name='change_percentage',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockimport',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=19),
        ),
    ]
