# Generated by Django 4.2.14 on 2024-08-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_stockimport_change_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockimport',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
