# Generated by Django 4.2.14 on 2024-08-08 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_stockimport_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockimport',
            name='status',
        ),
    ]
