# Generated by Django 4.2.14 on 2024-08-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_remove_stockimport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockimport',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.stock', unique_for_date='price'),
        ),
    ]
